# Generated by Django 3.0.14 on 2022-01-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orderdetails_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatched', 'dispatched'), ('delivered', 'delivered')], default='pending', max_length=30),
        ),
    ]
