# Generated by Django 3.0.14 on 2022-01-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderdetails_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='customer',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customer', to='app.Customer'),
        ),
    ]
